"""Tests for structured output tools with real LLM integration.

Tests each structured output tool individually using qwen3:0.6b to identify
which tools have issues with structured output parsing.
"""

import pytest
import asyncio
from typing import Dict, Any
from pydantic import ValidationError
from kai.core.agent import KaiAgent
from kai.core.orchestration.execution_context import ExecutionInputs, BacktrackingContext, ExecutionContext
from kai.core.orchestration.prompt_tools import (
    TaskListGenerationTool,
    TaskListCritiqueTool,
    ReasoningCritiqueTool,
    ErrorRecoveryTool,
    BacktrackRecoveryTool,
    AutonomousMarkCompletionTool,
    AutonomousUpdateTasksTool,
    AutonomousUpdateCritiqueTool,
    AutoLoopIntentClassificationTool,
    IntentClassificationTool,
    CellPositioningTool,
    CellSelectionDeletionTool,
    SectionCodeReviewTool,
    ReferenceWorkflowSelectionTool,
    ReferenceWorkflowCellSelectionTool
)
from kai.core.orchestration.base_tool import ToolOutputType


class TestStructuredOutputTools:
    """Test all structured output tools with real LLM."""

    @pytest.fixture
    def llm_interface(self):
        """Create LLM interface using smaller qwen model for testing."""
        agent = KaiAgent(llm_provider='ollama', model="qwen3:0.6b")
        return agent.llm_interface

    def create_basic_context(self, **kwargs) -> ExecutionContext:
        """Create basic execution context for tool testing."""
        context_fields = {
            "current_cell": "",
            "error_message": "",
            "execution_history": [],
            "conversation_history": [],
            "notebook_structure": {
                "totalCells": 3,
                "allCells": ["# Cell 1", "# Cell 2", "# Cell 3"]
            },
            "last_execution_failed": False,
            "autonomous_mode": True,
            "last_cell_modified_in_auto_mode": kwargs.get("last_cell_modified_in_auto_mode", None),
            **kwargs
        }

        exec_inputs = ExecutionInputs(
            user_query=kwargs.get("user_query", "Test query"),
            context=context_fields,
            task_list=kwargs.get("task_list", {"tasks": []}),
            backtracking_context=kwargs.get("backtracking_context", None)
        )

        return ExecutionContext(
            inputs=exec_inputs,
            session_metadata={"session_id": "test"}
        )

    @pytest.mark.asyncio
    @pytest.mark.parametrize("rag_enabled", [True, False])
    async def test_task_list_generation_tool(self, llm_interface, rag_enabled):
        """Test TaskListGenerationTool with real LLM, with and without RAG."""
        import json

        # TaskListGenerationTool now only requires llm_interface
        tool = TaskListGenerationTool(llm_interface)
        context = self.create_basic_context(
            user_query="Analyze single-cell RNA-seq data with quality control",
            rag_enabled=rag_enabled,
            reference_workflows="# Sample workflow\nload_data()\nqc_plots()" if rag_enabled else "",
            reference_workflow_annotation="Use standard QC patterns" if rag_enabled else ""
        )

        try:
            result = await tool.execute(context)

            # Basic structure validation
            assert result is not None
            assert hasattr(result, 'output_ui')
            assert hasattr(result, 'output_workflow')
            assert hasattr(result, 'output_type')

            # Validate output_ui structure
            ui_output = result.output_ui
            assert isinstance(ui_output, dict)
            assert 'text' in ui_output
            # reference_workflow_annotation no longer in ui_output - moved to separate tools

            # Validate task list JSON format
            task_list_json = ui_output['text']
            task_list = json.loads(task_list_json)
            assert 'tasks' in task_list
            assert isinstance(task_list['tasks'], list)
            assert len(task_list['tasks']) > 0

            # Validate each task has required fields
            for task in task_list['tasks']:
                assert 'id' in task
                assert 'task' in task
                assert 'status' in task
                assert isinstance(task['id'], int)
                assert isinstance(task['task'], str)
                assert task['status'] == 'pending'
                assert len(task['task'].strip()) > 0

            # Validate workflow output
            workflow_output = result.output_workflow
            assert isinstance(workflow_output, dict)
            assert 'task_list' in workflow_output
            # Note: reference_workflow_annotation, reference_workflow_content and reference_workflow_ids
            # are no longer generated by TaskListGenerationTool since it doesn't handle notebook selection
            # Those are now handled by ReferenceWorkflowSelectionTool and ReferenceWorkflowCellSelectionTool

            # Check retrieval queries if RAG enabled
            if rag_enabled:
                assert 'retrieval_queries' in workflow_output
            else:
                # May or may not have retrieval_queries when disabled
                pass

            print(f"TaskListGenerationTool (RAG={rag_enabled}) passed all validations")
            print(f"Generated {len(task_list['tasks'])} tasks")

        except Exception as e:
            pytest.fail(f"TaskListGenerationTool (RAG={rag_enabled}) failed with unexpected error: {e}")

    @pytest.mark.asyncio
    async def test_task_list_generation_tool_edge_cases(self, llm_interface):
        """Test TaskListGenerationTool handles edge cases properly."""
        import json

        # TaskListGenerationTool now only requires llm_interface
        tool = TaskListGenerationTool(llm_interface)

        # Test with empty reference workflows and no RAG
        context = self.create_basic_context(
            user_query="Simple data analysis task",
            rag_enabled=False,
            reference_workflows="",
            reference_workflow_annotation=""
        )

        try:
            result = await tool.execute(context)

            # Should still generate valid task list even without reference workflows
            assert result is not None
            ui_output = result.output_ui
            task_list = json.loads(ui_output['text'])
            assert len(task_list['tasks']) > 0

            # Workflow output should be present
            workflow_output = result.output_workflow
            assert 'task_list' in workflow_output
            # reference_workflow_annotation no longer in output - moved to separate tools

            print("TaskListGenerationTool handled edge case successfully")

        except Exception as e:
            pytest.fail(f"TaskListGenerationTool edge case failed: {e}")

    @pytest.mark.asyncio
    async def test_task_generation_tool_empty_tasks_exception(self, llm_interface):
        """Test TaskListGenerationTool raises exception when LLM returns empty task list."""
        from unittest.mock import Mock, AsyncMock

        # TaskListGenerationTool now only requires llm_interface
        tool = TaskListGenerationTool(llm_interface)
        context = self.create_basic_context(
            user_query="This query should result in empty task list",
            rag_enabled=False
        )

        # Mock the LLM provider to return empty task list
        mock_structured_result = Mock()
        mock_structured_result.tasks = []  # Empty tasks list
        mock_structured_result.reference_workflow_annotation = ""
        mock_structured_result.retrieval_queries = []

        # Mock the tool's llm_provider.generate_structured method
        original_generate_structured = tool.llm_provider.generate_structured
        tool.llm_provider.generate_structured = AsyncMock(return_value=mock_structured_result)

        try:
            # Should raise exception for empty task list
            with pytest.raises(Exception) as exc_info:
                await tool.execute(context)

            # Verify the exception message mentions empty tasks
            assert "empty" in str(exc_info.value).lower() or "no" in str(exc_info.value).lower()
            print("Empty task list validation works correctly")

        finally:
            # Restore original method
            tool.llm_provider.generate_structured = original_generate_structured

    @pytest.mark.asyncio
    async def test_error_recovery_tool(self, llm_interface):
        """Test ErrorRecoveryTool with real LLM."""
        tool = ErrorRecoveryTool(llm_interface)
        context = self.create_basic_context(
            error_message="NameError: name 'data_file' is not defined",
            last_execution_failed=True
        )

        try:
            result = await tool.execute(context)
            assert result is not None
            assert hasattr(result, 'output_ui')
            print(f"ErrorRecoveryTool result: {result.output_ui}")
        except Exception as e:
            pytest.fail(f"ErrorRecoveryTool failed with unexpected error: {e}")

    @pytest.mark.asyncio
    async def test_autonomous_mark_completion_tool(self, llm_interface):
        """Test AutonomousMarkCompletionTool with real LLM."""
        tool = AutonomousMarkCompletionTool(llm_interface)
        context = self.create_basic_context(
            task_list={
                "tasks": [
                    {"id": 1, "task": "Load data", "status": "active"},
                    {"id": 2, "task": "Process data", "status": "pending"}
                ]
            },
            execution_result="Successfully loaded CSV with 1000 rows"
        )

        # Patch the LLM provider to capture raw output
        provider = llm_interface.provider_small
        original_generate_structured = provider.generate_structured
        captured_responses = []

        async def capture_generate_structured(*args, **kwargs):
            try:
                result = await original_generate_structured(*args, **kwargs)
                captured_responses.append(("SUCCESS", result))
                return result
            except Exception as e:
                # Capture the raw response if available
                raw_response = getattr(e, 'raw_output', str(e))
                captured_responses.append(("ERROR", str(e), raw_response))
                raise

        provider.generate_structured = capture_generate_structured

        try:
            result = await tool.execute(context)
            assert result is not None
            assert hasattr(result, 'output_ui')
            print(f"AutonomousMarkCompletionTool result: {result.output_ui}")

            # Show captured raw outputs
            for i, capture in enumerate(captured_responses):
                if capture[0] == "SUCCESS":
                    print(f"Capture {i+1}: SUCCESS - Parsed result: {capture[1]}")
                else:
                    print(f"Capture {i+1}: ERROR - {capture[1]}")
                    if len(capture) > 2:
                        print(f"Raw LLM output: {repr(capture[2])}")

        except Exception as e:
            # Show captured outputs even on exception
            for i, capture in enumerate(captured_responses):
                if capture[0] == "SUCCESS":
                    print(f"Capture {i+1}: SUCCESS - Parsed result: {capture[1]}")
                else:
                    print(f"Capture {i+1}: ERROR - {capture[1]}")
                    if len(capture) > 2:
                        print(f"Raw LLM output: {repr(capture[2])}")
            pytest.fail(f"AutonomousMarkCompletionTool failed with unexpected error: {e}")
        finally:
            # Restore original method
            provider.generate_structured = original_generate_structured

    @pytest.mark.asyncio
    @pytest.mark.parametrize("task_state", ["simple", "complex", "error_case"])
    async def test_autonomous_mark_completion_tool_scenarios(self, llm_interface, task_state):
        """Test AutonomousMarkCompletionTool with different task scenarios."""
        tool = AutonomousMarkCompletionTool(llm_interface)

        if task_state == "simple":
            context = self.create_basic_context(
                task_list={
                    "tasks": [
                        {"id": 1, "task": "Load data", "status": "active"}
                    ]
                },
                execution_result="Success: data loaded"
            )
        elif task_state == "complex":
            context = self.create_basic_context(
                task_list={
                    "tasks": [
                        {"id": 1, "task": "Load and preprocess single-cell RNA-seq data", "status": "active"},
                        {"id": 2, "task": "Perform quality control and filtering", "status": "active"},
                        {"id": 3, "task": "Normalize and scale data", "status": "pending"},
                        {"id": 4, "task": "Run dimensionality reduction", "status": "pending"}
                    ]
                },
                execution_result="Successfully loaded 15,000 cells with 25,000 genes"
            )
        else:  # error_case
            context = self.create_basic_context(
                task_list={
                    "tasks": [
                        {"id": 1, "task": "Load data", "status": "active"},
                        {"id": 2, "task": "Process data", "status": "pending"}
                    ]
                },
                execution_result="Error: file not found"
            )

        try:
            result = await tool.execute(context)
            assert result is not None
            assert hasattr(result, 'output_ui')
            print(f"AutonomousMarkCompletionTool ({task_state}) result: {result.output_ui}")
        except Exception as e:
            pytest.fail(f"AutonomousMarkCompletionTool ({task_state}) failed with unexpected error: {e}")

    @pytest.mark.asyncio
    @pytest.mark.parametrize("rag_enabled", [True, False])
    async def test_autonomous_update_tasks_tool(self, llm_interface, rag_enabled):
        """Test AutonomousUpdateTasksTool with real LLM, with and without RAG."""
        tool = AutonomousUpdateTasksTool(llm_interface)
        context = self.create_basic_context(
            task_list={
                "tasks": [
                    {"id": 1, "task": "Load data", "status": "completed"},
                    {"id": 2, "task": "Process data", "status": "active"}
                ]
            },
            rag_enabled=rag_enabled,
            reference_workflows="# Standard analysis pattern\nload_data()\nprocess_data()" if rag_enabled else "",
            reference_workflow_annotation="Follow established patterns" if rag_enabled else ""
        )

        try:
            result = await tool.execute(context)
            assert result is not None
            assert hasattr(result, 'output_ui')
            print(f"AutonomousUpdateTasksTool (RAG={rag_enabled}) result: {result.output_ui}")
        except Exception as e:
            pytest.fail(f"AutonomousUpdateTasksTool (RAG={rag_enabled}) failed with unexpected error: {e}")

    @pytest.mark.asyncio
    @pytest.mark.parametrize("update_rule", ["KEEP", "UPDATE"])
    async def test_autonomous_update_tasks_tool_update_rule(self, llm_interface, update_rule):
        """Test AutonomousUpdateTasksTool KEEP vs UPDATE logic with mocked responses."""
        from unittest.mock import Mock, AsyncMock
        from kai.core.orchestration.schemas import AutonomousTaskUpdate, TaskItem

        tool = AutonomousUpdateTasksTool(llm_interface)

        # Original task list with completed and active tasks
        original_task_list = {
            "tasks": [
                {"id": 1, "task": "Load data", "status": "completed"},
                {"id": 2, "task": "Process data", "status": "completed"},
                {"id": 3, "task": "Analyze data", "status": "active"},
                {"id": 4, "task": "Generate plots", "status": "pending"}
            ]
        }

        context = self.create_basic_context(
            task_list=original_task_list,
            rag_enabled=True,  # Enable RAG to test query handling
            last_execution_failed=False
        )

        # Mock structured response based on update_rule
        if update_rule == "KEEP":
            # KEEP should preserve original task list
            mock_result = AutonomousTaskUpdate(
                tasks=[
                    TaskItem(id=3, task="Analyze data", status="active"),
                    TaskItem(id=4, task="Generate plots", status="pending")
                ],
                retrieval_queries=["test query"],
                update_rationale="Keeping existing task structure as no changes needed",
                update_rule="KEEP"
            )
            expected_task_count = 4  # All original tasks preserved
            expected_completed_count = 2  # Original completed tasks preserved
        else:
            # UPDATE should apply new task structure
            mock_result = AutonomousTaskUpdate(
                tasks=[
                    TaskItem(id=3, task="Enhanced data analysis", status="active"),
                    TaskItem(id=4, task="Create visualizations", status="pending"),
                    TaskItem(id=5, task="Write summary report", status="pending")
                ],
                retrieval_queries=["enhanced analysis"],
                update_rationale="Updated task list to include enhanced analysis and reporting",
                update_rule="UPDATE"
            )
            expected_task_count = 5  # 2 completed + 3 new tasks
            expected_completed_count = 2  # Original completed tasks preserved

        # Mock the LLM provider to return our controlled response
        original_generate_structured = tool.llm_provider.generate_structured
        tool.llm_provider.generate_structured = AsyncMock(return_value=mock_result)

        try:
            result = await tool.execute(context)

            # Validate result structure
            assert result is not None
            assert hasattr(result, 'output_workflow')
            assert hasattr(result, 'output_ui')

            # Check workflow output
            workflow_output = result.output_workflow
            assert "task_list" in workflow_output

            # Parse the updated task list
            updated_task_list = workflow_output["task_list"]
            updated_tasks = updated_task_list["tasks"]

            # Validate task count
            assert len(updated_tasks) == expected_task_count, f"Expected {expected_task_count} tasks, got {len(updated_tasks)}"

            # Count completed tasks (should always preserve completed ones)
            completed_tasks = [t for t in updated_tasks if t["status"] == "completed"]
            assert len(completed_tasks) == expected_completed_count, f"Expected {expected_completed_count} completed tasks, got {len(completed_tasks)}"

            # Validate completed tasks are preserved with original IDs
            if expected_completed_count > 0:
                assert completed_tasks[0]["id"] == 1
                assert completed_tasks[0]["task"] == "Load data"
                assert completed_tasks[1]["id"] == 2
                assert completed_tasks[1]["task"] == "Process data"

            if update_rule == "KEEP":
                # For KEEP: verify exact preservation of original task list
                assert updated_tasks == original_task_list["tasks"]
                print(f"KEEP test passed: Task list preserved exactly")
            else:
                # For UPDATE: verify completed tasks preserved + new tasks added
                non_completed_tasks = [t for t in updated_tasks if t["status"] != "completed"]
                assert len(non_completed_tasks) == 3  # 3 new tasks from mock
                assert non_completed_tasks[0]["task"] == "Enhanced data analysis"
                assert non_completed_tasks[1]["task"] == "Create visualizations"
                assert non_completed_tasks[2]["task"] == "Write summary report"
                print(f"UPDATE test passed: Completed tasks preserved, new tasks added")

            # Check RAG query handling
            if mock_result.retrieval_queries:
                assert "snippet_retrieval_query" in workflow_output
                assert workflow_output["snippet_retrieval_query"] == mock_result.retrieval_queries

            print(f"AutonomousUpdateTasksTool ({update_rule}) validation successful")

        except Exception as e:
            pytest.fail(f"AutonomousUpdateTasksTool ({update_rule}) failed: {e}")
        finally:
            # Restore original method
            tool.llm_provider.generate_structured = original_generate_structured

    @pytest.mark.asyncio
    async def test_autonomous_update_critique_tool(self, llm_interface):
        """Test AutonomousUpdateCritiqueTool with real LLM."""
        tool = AutonomousUpdateCritiqueTool(llm_interface)
        context = self.create_basic_context(
            task_list={
                "tasks": [
                    {"id": 1, "task": "Load single-cell RNA-seq data", "status": "completed"},
                    {"id": 2, "task": "Perform quality control filtering", "status": "pending"},
                    {"id": 3, "task": "Normalize and scale data", "status": "pending"}
                ]
            },
            user_query="Update the task list to include visualization steps"
        )

        # Patch the LLM provider to capture raw output for debugging
        provider = llm_interface.provider_small
        original_generate_structured = provider.generate_structured
        captured_responses = []

        async def capture_generate_structured(*args, **kwargs):
            try:
                result = await original_generate_structured(*args, **kwargs)
                captured_responses.append(("SUCCESS", result))
                return result
            except Exception as e:
                # Capture the raw response if available
                raw_response = getattr(e, 'raw_output', str(e))
                captured_responses.append(("ERROR", str(e), raw_response))
                raise

        provider.generate_structured = capture_generate_structured

        try:
            result = await tool.execute(context)
            assert result is not None
            assert hasattr(result, 'output_workflow')

            # Check that the expected keys are present in the workflow output
            workflow_output = result.output_workflow
            assert "autonomous_update_approval" in workflow_output
            assert "autonomous_update_critique" in workflow_output

            print(f"AutonomousUpdateCritiqueTool result: {workflow_output}")

            # Show captured raw outputs
            for i, capture in enumerate(captured_responses):
                if capture[0] == "SUCCESS":
                    print(f"Capture {i+1}: SUCCESS - Parsed result: {capture[1]}")
                else:
                    print(f"Capture {i+1}: ERROR - {capture[1]}")
                    if len(capture) > 2:
                        print(f"Raw LLM output: {repr(capture[2])}")

        except Exception as e:
            # Show captured outputs even on exception
            for i, capture in enumerate(captured_responses):
                if capture[0] == "SUCCESS":
                    print(f"Capture {i+1}: SUCCESS - Parsed result: {capture[1]}")
                else:
                    print(f"Capture {i+1}: ERROR - {capture[1]}")
                    if len(capture) > 2:
                        print(f"Raw LLM output: {repr(capture[2])}")
            pytest.fail(f"AutonomousUpdateCritiqueTool failed with unexpected error: {e}")
        finally:
            # Restore original method
            provider.generate_structured = original_generate_structured

    @pytest.mark.asyncio
    async def test_autonomous_update_critique_tool_approved(self, llm_interface):
        """Test AutonomousUpdateCritiqueTool with APPROVED scenario."""
        tool = AutonomousUpdateCritiqueTool(llm_interface)
        context = self.create_basic_context(
            task_list={
                "tasks": [
                    {"id": 1, "task": "Load single-cell RNA-seq data", "status": "completed"},
                    {"id": 2, "task": "Perform quality control filtering", "status": "pending"},
                    {"id": 3, "task": "Normalize and scale data", "status": "pending"}
                ]
            },
            user_query="Add visualization steps to the existing task list"
        )

        # Mock the tool's LLM provider to return APPROVED result
        original_generate_structured = tool.llm_provider.generate_structured

        async def mock_approved_response(*args, **kwargs):
            from kai.core.orchestration.schemas import AutonomousUpdateCritique
            return AutonomousUpdateCritique(
                approval="APPROVED",
                critique=""
            )

        tool.llm_provider.generate_structured = mock_approved_response

        try:
            result = await tool.execute(context)
            assert result is not None
            assert hasattr(result, 'output_workflow')

            workflow_output = result.output_workflow
            assert "autonomous_update_approval" in workflow_output
            assert "autonomous_update_critique" in workflow_output
            assert workflow_output["autonomous_update_approval"] == "APPROVED"
            assert workflow_output["autonomous_update_critique"] == ""

            # For approved updates with no critique, should have NO_OUTPUT
            assert result.output_type == ToolOutputType.NO_OUTPUT
            assert result.output_ui == {}

            print(f"AutonomousUpdateCritiqueTool APPROVED result: {workflow_output}")

        finally:
            tool.llm_provider.generate_structured = original_generate_structured

    @pytest.mark.asyncio
    async def test_autonomous_update_critique_tool_modify(self, llm_interface):
        """Test AutonomousUpdateCritiqueTool with MODIFY scenario."""
        tool = AutonomousUpdateCritiqueTool(llm_interface)
        context = self.create_basic_context(
            task_list={
                "tasks": [
                    {"id": 1, "task": "Load data", "status": "pending"},
                    {"id": 2, "task": "Process data", "status": "pending"}
                ]
            },
            user_query="Add more specific analysis steps"
        )

        # Mock the tool's LLM provider to return MODIFY result with critique
        original_generate_structured = tool.llm_provider.generate_structured

        test_critique = "The proposed updates are too generic. Please specify exactly what type of quality control metrics to calculate and which normalization methods to use."

        async def mock_modify_response(*args, **kwargs):
            from kai.core.orchestration.schemas import AutonomousUpdateCritique
            return AutonomousUpdateCritique(
                approval="MODIFY",
                critique=test_critique
            )

        tool.llm_provider.generate_structured = mock_modify_response

        try:
            result = await tool.execute(context)
            assert result is not None
            assert hasattr(result, 'output_workflow')

            workflow_output = result.output_workflow
            assert "autonomous_update_approval" in workflow_output
            assert "autonomous_update_critique" in workflow_output
            assert workflow_output["autonomous_update_approval"] == "MODIFY"
            assert workflow_output["autonomous_update_critique"] == test_critique

            # For modify with critique, should have TASK_LIST_DISPLAY output
            assert result.output_type == ToolOutputType.TASK_LIST_DISPLAY
            assert "critique" in result.output_ui
            assert result.output_ui["critique"] == test_critique

            print(f"AutonomousUpdateCritiqueTool MODIFY result: {workflow_output}")

        finally:
            tool.llm_provider.generate_structured = original_generate_structured

    @pytest.mark.asyncio
    async def test_autonomous_update_critique_tool_empty_critique(self, llm_interface):
        """Test AutonomousUpdateCritiqueTool with empty critique handling."""
        tool = AutonomousUpdateCritiqueTool(llm_interface)
        context = self.create_basic_context(
            task_list={"tasks": [{"id": 1, "task": "Test task", "status": "pending"}]},
            user_query="Update task list"
        )

        # Mock the tool's LLM provider to return APPROVED with whitespace critique
        original_generate_structured = tool.llm_provider.generate_structured

        async def mock_empty_critique_response(*args, **kwargs):
            from kai.core.orchestration.schemas import AutonomousUpdateCritique
            return AutonomousUpdateCritique(
                approval="APPROVED",  # Valid value
                critique="   "  # Only whitespace
            )

        tool.llm_provider.generate_structured = mock_empty_critique_response

        try:
            result = await tool.execute(context)
            assert result is not None

            workflow_output = result.output_workflow
            # Should strip whitespace from critique
            assert workflow_output["autonomous_update_approval"] == "APPROVED"
            assert workflow_output["autonomous_update_critique"] == ""

            # Empty critique should result in NO_OUTPUT
            assert result.output_type == ToolOutputType.NO_OUTPUT
            assert result.output_ui == {}

            print(f"AutonomousUpdateCritiqueTool empty critique result: {workflow_output}")

        finally:
            tool.llm_provider.generate_structured = original_generate_structured

    @pytest.mark.asyncio
    async def test_task_list_critique_tool_approved(self, llm_interface):
        """Test TaskListCritiqueTool with APPROVED scenario."""
        tool = TaskListCritiqueTool(llm_interface)
        context = self.create_basic_context(
            task_list={
                "tasks": [
                    {"id": 1, "task": "Load single-cell RNA-seq data", "status": "pending"},
                    {"id": 2, "task": "Perform quality control filtering", "status": "pending"},
                    {"id": 3, "task": "Normalize and scale data", "status": "pending"}
                ]
            },
            user_query="Create a comprehensive analysis pipeline for single-cell data"
        )

        # Mock the tool's LLM provider to return APPROVED result
        original_generate_structured = tool.llm_provider.generate_structured

        async def mock_approved_response(*args, **kwargs):
            from kai.core.orchestration.schemas import TaskListCritique
            return TaskListCritique(
                approval="APPROVED",
                critique=""
            )

        tool.llm_provider.generate_structured = mock_approved_response

        try:
            result = await tool.execute(context)
            assert result is not None
            assert hasattr(result, 'output_workflow')

            workflow_output = result.output_workflow
            assert "task_list_approval" in workflow_output
            assert "task_list_critique" in workflow_output
            assert workflow_output["task_list_approval"] == "APPROVED"
            assert workflow_output["task_list_critique"] == ""

            # For approved tasks with no critique, should have NO_OUTPUT
            assert result.output_type == ToolOutputType.NO_OUTPUT
            assert result.output_ui == {}

            print(f"TaskListCritiqueTool APPROVED result: {workflow_output}")

        finally:
            tool.llm_provider.generate_structured = original_generate_structured

    @pytest.mark.asyncio
    async def test_task_list_critique_tool_modify(self, llm_interface):
        """Test TaskListCritiqueTool with MODIFY scenario."""
        tool = TaskListCritiqueTool(llm_interface)
        context = self.create_basic_context(
            task_list={
                "tasks": [
                    {"id": 1, "task": "Load data", "status": "pending"}
                ]
            },
            user_query="Analyze single-cell RNA-seq data"
        )

        # Mock the tool's LLM provider to return MODIFY result with critique
        original_generate_structured = tool.llm_provider.generate_structured

        test_critique = "The task list is too vague. Please add specific steps for quality control, normalization, and visualization."

        async def mock_modify_response(*args, **kwargs):
            from kai.core.orchestration.schemas import TaskListCritique
            return TaskListCritique(
                approval="MODIFY",
                critique=test_critique
            )

        tool.llm_provider.generate_structured = mock_modify_response

        try:
            result = await tool.execute(context)
            assert result is not None
            assert hasattr(result, 'output_workflow')

            workflow_output = result.output_workflow
            assert "task_list_approval" in workflow_output
            assert "task_list_critique" in workflow_output
            assert workflow_output["task_list_approval"] == "MODIFY"
            assert workflow_output["task_list_critique"] == test_critique

            # For modify with critique, should have TASK_LIST_DISPLAY output
            assert result.output_type == ToolOutputType.TASK_LIST_DISPLAY
            assert "critique" in result.output_ui
            assert result.output_ui["critique"] == test_critique

            print(f"TaskListCritiqueTool MODIFY result: {workflow_output}")

        finally:
            tool.llm_provider.generate_structured = original_generate_structured

    @pytest.mark.asyncio
    async def test_task_list_critique_tool_empty_critique(self, llm_interface):
        """Test TaskListCritiqueTool with empty critique handling."""
        tool = TaskListCritiqueTool(llm_interface)
        context = self.create_basic_context(
            task_list={"tasks": [{"id": 1, "task": "Test task", "status": "pending"}]},
            user_query="Test query"
        )

        # Mock the tool's LLM provider to return APPROVED with whitespace critique
        original_generate_structured = tool.llm_provider.generate_structured

        async def mock_empty_critique_response(*args, **kwargs):
            from kai.core.orchestration.schemas import TaskListCritique
            return TaskListCritique(
                approval="APPROVED",  # Valid value
                critique="   "  # Only whitespace
            )

        tool.llm_provider.generate_structured = mock_empty_critique_response

        try:
            result = await tool.execute(context)
            assert result is not None

            workflow_output = result.output_workflow
            # Should strip whitespace from critique
            assert workflow_output["task_list_approval"] == "APPROVED"
            assert workflow_output["task_list_critique"] == ""

            # Empty critique should result in NO_OUTPUT
            assert result.output_type == ToolOutputType.NO_OUTPUT
            assert result.output_ui == {}

            print(f"TaskListCritiqueTool empty critique result: {workflow_output}")

        finally:
            tool.llm_provider.generate_structured = original_generate_structured

    @pytest.mark.asyncio
    async def test_task_list_critique_tool_validation_error(self, llm_interface):
        """Test TaskListCritiqueTool with Pydantic validation errors."""
        tool = TaskListCritiqueTool(llm_interface)
        context = self.create_basic_context(
            task_list={"tasks": [{"id": 1, "task": "Test task", "status": "pending"}]},
            user_query="Test query"
        )

        # Mock the tool's LLM provider to return invalid approval value
        original_generate_structured = tool.llm_provider.generate_structured

        async def mock_invalid_response(*args, **kwargs):
            # Simulate an error during LLM response parsing
            raise ValueError("Invalid approval value: must be APPROVED or MODIFY")

        tool.llm_provider.generate_structured = mock_invalid_response

        try:
            # Now that we removed the try-catch, the tool should raise the exception
            # instead of returning an error ToolResult
            with pytest.raises(ValueError, match="Invalid approval value"):
                await tool.execute(context)
            print("✓ TaskListCritiqueTool correctly raises exceptions instead of silently approving")

        finally:
            tool.llm_provider.generate_structured = original_generate_structured

    @pytest.mark.asyncio
    async def test_intent_classification_tool(self, llm_interface):
        """Test IntentClassificationTool with real LLM."""
        tool = IntentClassificationTool(llm_interface)
        context = self.create_basic_context(
            user_query="Generate a scatter plot of the data"
        )

        try:
            result = await tool.execute(context)
            assert result is not None
            assert hasattr(result, 'output_ui')
            print(f"IntentClassificationTool result: {result.output_ui}")
        except Exception as e:
            pytest.fail(f"IntentClassificationTool failed with unexpected error: {e}")

    @pytest.mark.asyncio
    async def test_feedback_intent_classification_tool(self, llm_interface):
        """Test FeedbackIntentClassificationTool with real LLM."""
        tool = AutoLoopIntentClassificationTool(llm_interface)
        context = self.create_basic_context(
            user_query="Change the method from t-test to wilcoxon",
            task_list={
                "tasks": [
                    {"id": 1, "task": "Run differential expression analysis", "status": "active"}
                ]
            }
        )

        try:
            result = await tool.execute(context)
            assert result is not None
            assert hasattr(result, 'output_ui')
            print(f"FeedbackIntentClassificationTool result: {result.output_ui}")
        except Exception as e:
            pytest.fail(f"FeedbackIntentClassificationTool failed with unexpected error: {e}")

    @pytest.mark.asyncio
    async def test_cell_positioning_tool(self, llm_interface):
        """Test CellPositioningTool with real LLM."""
        tool = CellPositioningTool(llm_interface)
        context = self.create_basic_context(
            user_query="Add the code after the data loading cell"
        )

        try:
            result = await tool.execute(context)
            assert result is not None
            assert hasattr(result, 'output_ui')
            print(f"CellPositioningTool result: {result.output_ui}")

            # Check positioning result
            result_data = result.output_ui
            if isinstance(result_data, dict) and 'target_cell' in result_data:
                target_cell = result_data['target_cell']
                print(f"Target cell position: {target_cell}")
                assert target_cell != -1, "Cell position should not be -1"
                assert isinstance(target_cell, int), "Target cell should be an integer"

        except Exception as e:
            pytest.fail(f"CellPositioningTool failed with unexpected error: {e}")

    @pytest.mark.asyncio
    async def test_cell_selection_deletion_tool(self, llm_interface):
        """Test CellSelectionDeletionTool with real LLM."""
        tool = CellSelectionDeletionTool(llm_interface)
        context = self.create_basic_context(
            user_query="Remove the empty cells and duplicated imports",
            reset_tasks=[{"id": 1, "task": "Load data"}, {"id": 2, "task": "Clean data"}],
            backtracking_context=BacktrackingContext(
                recovery_objective="Need to reload data with correct format",
                backtrack_to_task={"id": 1, "task": "Load data"}
            )
        )

        try:
            result = await tool.execute(context)
            assert result is not None
            assert hasattr(result, 'output_ui')
            print(f"CellSelectionDeletionTool result: {result.output_ui}")
        except Exception as e:
            pytest.fail(f"CellSelectionDeletionTool failed with unexpected error: {e}")

    @pytest.mark.asyncio
    async def test_reference_workflow_selection_tool(self, llm_interface):
        """Test ReferenceWorkflowSelectionTool with real LLM."""
        # This test requires notebook storage setup, so let's create a minimal version
        from kai.retrieval.workflow_summaries.notebook_storage import NotebookStorage
        from kai.retrieval.workflow_summaries.summary_search import WorkflowSummaryRag
        from kai.retrieval.workflow_summaries.notebook_selector import NotebookSelector
        from pathlib import Path

        # Create temporary storage for test
        storage_path = Path("/tmp/test_notebook_storage")
        storage_path.mkdir(exist_ok=True)

        try:
            notebook_storage = NotebookStorage(storage_path)
            summary_search = WorkflowSummaryRag(storage_path)
            notebook_selector = NotebookSelector(notebook_storage)

            from kai.core.prompt_manager import PromptScenario
            tool = ReferenceWorkflowSelectionTool(
                PromptScenario.REFERENCE_WORKFLOW_SELECTION,
                llm_interface,
                notebook_selector
            )
            context = self.create_basic_context(
                user_query="Analyze single-cell RNA-seq data"
            )

            result = await tool.execute(context)
            assert result is not None
            assert hasattr(result, 'output_ui')
            print(f"ReferenceWorkflowSelectionTool result: {result.output_ui}")

        except Exception as e:
            pytest.fail(f"ReferenceWorkflowSelectionTool failed with unexpected error: {e}")
        finally:
            # Cleanup
            import shutil
            if storage_path.exists():
                shutil.rmtree(storage_path, ignore_errors=True)

    @pytest.mark.asyncio
    async def test_reference_workflow_cell_selection_tool(self, llm_interface):
        """Test ReferenceWorkflowCellSelectionTool with mocked notebook data."""
        from kai.retrieval.workflow_summaries.notebook_storage import NotebookStorage
        from kai.retrieval.workflow_summaries.notebook_selector import NotebookSelector
        from kai.core.prompt_manager import PromptScenario
        from unittest.mock import Mock, AsyncMock
        from kai.core.orchestration.schemas import ReferenceWorkflowCellSelection
        from pathlib import Path

        # Create temporary storage for test
        storage_path = Path("/tmp/test_notebook_storage")
        storage_path.mkdir(exist_ok=True)

        try:
            # Create mock notebook data
            mock_notebook_data = {
                "metadata": {
                    "source_repository": "test-org/test-repo",
                    "workflow_filename": "test_workflow.ipynb",
                    "title": "Test Workflow"
                },
                "cells": [
                    {"order": 0, "content": "import scanpy as sc", "section": "imports"},
                    {"order": 1, "content": "import pandas as pd", "section": "imports"},
                    {"order": 2, "content": "# Load data", "section": "main"},
                    {"order": 3, "content": "adata = sc.read_h5ad('data.h5ad')", "section": "main"},
                    {"order": 4, "content": "# QC metrics", "section": "qc"},
                    {"order": 5, "content": "sc.pp.calculate_qc_metrics(adata)", "section": "qc"},
                    {"order": 6, "content": "# Plotting", "section": "visualization"},
                    {"order": 7, "content": "sc.pl.umap(adata)", "section": "visualization"}
                ]
            }

            notebook_storage = NotebookStorage(storage_path)
            notebook_selector = NotebookSelector(notebook_storage)

            # Mock the storage to return our test notebook
            notebook_storage.get_notebook_content = Mock(return_value=mock_notebook_data)

            tool = ReferenceWorkflowCellSelectionTool(
                PromptScenario.REFERENCE_WORKFLOW_CELL_SELECTION,
                llm_interface,
                notebook_selector
            )

            # Create context with reference workflow IDs
            context = self.create_basic_context(
                user_query="Perform single-cell RNA-seq analysis with quality control",
                reference_workflow_ids="test-org/test-repo/test_workflow.ipynb"
            )
            # Add internal IDs to context (normally set by ReferenceWorkflowSelectionTool)
            context.inputs.context["reference_workflow_internal_ids"] = ["test_workflow"]

            # Add unfiltered reference_workflow_content dict (normally set by ReferenceWorkflowSelectionTool)
            # This is required for ReferenceWorkflowCellSelectionTool to process
            unfiltered_content = "\n\n".join([
                f"Cell at index {cell['order']}:\n{cell['content']}"
                for cell in mock_notebook_data["cells"]
            ])
            context.inputs.context["reference_workflow_content"] = {
                "test_workflow": unfiltered_content
            }

            # Mock the LLM response to select specific cells
            mock_cell_selection = ReferenceWorkflowCellSelection(
                selected_cells=[0, 1, 3, 4, 5]  # Select imports, data loading, and QC cells
            )

            # Mock at the correct level - llm_provider.generate_structured
            call_count = 0
            original_generate = tool.llm_provider.generate_structured

            async def mock_generate(*args, **kwargs):
                nonlocal call_count
                call_count += 1
                return mock_cell_selection

            tool.llm_provider.generate_structured = mock_generate

            result = await tool.execute(context)

            # Verify LLM was called exactly once (one notebook)
            assert call_count == 1, f"Expected LLM to be called once, but was called {call_count} times"

            # Verify context was cleaned up after execution
            assert "current_notebook_for_cell_selection" not in context.inputs.context, \
                "current_notebook_for_cell_selection should be cleaned up after execution"

            # Validate result
            assert result is not None
            assert hasattr(result, 'output_workflow')

            # Check that reference_workflow_content was updated
            workflow_output = result.output_workflow
            assert "reference_workflow_content" in workflow_output

            # The content is a dict mapping internal_id -> filtered_content
            content_dict = workflow_output["reference_workflow_content"]
            assert isinstance(content_dict, dict)
            assert "test_workflow" in content_dict

            # Get the filtered content for our test notebook
            content = content_dict["test_workflow"]
            assert isinstance(content, str)

            # Verify selected cells are in the content
            assert "Cell at index 0" in content  # import scanpy
            assert "Cell at index 1" in content  # import pandas
            assert "Cell at index 3" in content  # Load data
            assert "Cell at index 4" in content  # QC metrics
            assert "Cell at index 5" in content  # calculate_qc_metrics

            # Verify excluded cells are NOT in the content
            assert "Cell at index 2" not in content  # Comment cell
            assert "Cell at index 6" not in content  # Plotting comment
            assert "Cell at index 7" not in content  # umap plot

            # Verify the specific cells that should be excluded are truly excluded
            # by checking their unique content is not present
            assert "# Load data" not in content  # Cell 2 comment
            assert "# Plotting" not in content  # Cell 6 comment
            assert "sc.pl.umap" not in content  # Cell 7 plotting code

            # Verify UI output includes percentage information as bullet list
            assert hasattr(result, 'output_ui')
            ui_output = result.output_ui
            assert 'text' in ui_output

            # Should show notebook ID with percentage (5/8 = 62.5% ≈ 62%) in bullet format
            notebook_message = ui_output['text']
            assert "test-org/test-repo/test_workflow.ipynb" in notebook_message
            assert "62%" in notebook_message or "63%" in notebook_message  # Allow rounding variation

            # Verify bullet list format (starts with "📚 ")
            assert notebook_message.startswith("📚 "), "Output should be formatted with book emoji"

            # Verify output type is REFERENCE_WORKFLOWS (not NO_OUTPUT)
            assert result.output_type == ToolOutputType.REFERENCE_WORKFLOWS

            print(f"✓ ReferenceWorkflowCellSelectionTool successfully filtered cells")
            print(f"✓ LLM called {call_count} time(s)")
            print(f"✓ Selected {len(mock_cell_selection.selected_cells)} out of {len(mock_notebook_data['cells'])} cells")
            print(f"✓ Context properly managed and cleaned up")
            print(f"✓ UI message:\n{notebook_message}")

        except Exception as e:
            pytest.fail(f"ReferenceWorkflowCellSelectionTool failed with unexpected error: {e}")
        finally:
            # Restore original method
            tool.llm_provider.generate_structured = original_generate

            # Cleanup storage
            import shutil
            if storage_path.exists():
                shutil.rmtree(storage_path, ignore_errors=True)

    @pytest.mark.asyncio
    async def test_reference_workflow_cell_selection_multiple_notebooks(self, llm_interface):
        """Test ReferenceWorkflowCellSelectionTool with multiple notebooks."""
        from kai.retrieval.workflow_summaries.notebook_storage import NotebookStorage
        from kai.retrieval.workflow_summaries.notebook_selector import NotebookSelector
        from kai.core.prompt_manager import PromptScenario
        from unittest.mock import Mock, AsyncMock
        from kai.core.orchestration.schemas import ReferenceWorkflowCellSelection
        from pathlib import Path

        storage_path = Path("/tmp/test_notebook_storage_multi")
        storage_path.mkdir(exist_ok=True)

        try:
            # Create two mock notebooks
            notebook1 = {
                "metadata": {"source_repository": "org1/repo1", "workflow_filename": "workflow1.ipynb", "title": "Workflow 1"},
                "cells": [{"order": i, "content": f"cell {i}", "section": "main"} for i in range(5)]
            }
            notebook2 = {
                "metadata": {"source_repository": "org2/repo2", "workflow_filename": "workflow2.ipynb", "title": "Workflow 2"},
                "cells": [{"order": i, "content": f"cell {i}", "section": "main"} for i in range(10)]
            }

            notebook_storage = NotebookStorage(storage_path)
            notebook_selector = NotebookSelector(notebook_storage)

            # Mock storage to return both notebooks
            def mock_get_content(notebook_id):
                if notebook_id == "workflow1":
                    return notebook1
                elif notebook_id == "workflow2":
                    return notebook2
                return None

            notebook_storage.get_notebook_content = Mock(side_effect=mock_get_content)

            tool = ReferenceWorkflowCellSelectionTool(
                PromptScenario.REFERENCE_WORKFLOW_CELL_SELECTION,
                llm_interface,
                notebook_selector
            )

            # Context with TWO notebooks - order matters for zip!
            context = self.create_basic_context(
                user_query="Test query",
                reference_workflow_ids="org1/repo1/workflow1.ipynb, org2/repo2/workflow2.ipynb"
            )
            context.inputs.context["reference_workflow_internal_ids"] = ["workflow1", "workflow2"]
            context.inputs.context["reference_workflow_content"] = {
                "workflow1": "> Notebook ID: org1/repo1/workflow1.ipynb\n>> Cell 0\ncell 0\n>> Cell 1\ncell 1\n>> Cell 2\ncell 2\n>> Cell 3\ncell 3\n>> Cell 4\ncell 4",
                "workflow2": "> Notebook ID: org2/repo2/workflow2.ipynb\n>> Cell 0\ncell 0\n>> Cell 1\ncell 1\n>> Cell 2\ncell 2\n>> Cell 3\ncell 3\n>> Cell 4\ncell 4\n>> Cell 5\ncell 5\n>> Cell 6\ncell 6\n>> Cell 7\ncell 7\n>> Cell 8\ncell 8\n>> Cell 9\ncell 9"
            }

            # Mock LLM to return different selections for each notebook
            call_count = 0
            original_generate = tool.llm_provider.generate_structured

            async def mock_generate(*args, **kwargs):
                nonlocal call_count
                call_count += 1
                if call_count == 1:
                    return ReferenceWorkflowCellSelection(selected_cells=[0, 2, 4])  # 3/5 = 60%
                else:
                    return ReferenceWorkflowCellSelection(selected_cells=[1, 3, 5, 7, 9])  # 5/10 = 50%

            tool.llm_provider.generate_structured = mock_generate

            result = await tool.execute(context)

            # Verify LLM called twice
            assert call_count == 2

            # Verify UI output has BOTH notebooks in alphabetical order with correct percentages
            ui_text = result.output_ui['text']
            lines = ui_text.strip().split('\n')
            assert len(lines) == 2

            # Should be sorted: org1 before org2
            assert "org1/repo1/workflow1.ipynb" in lines[0] and "60%" in lines[0]
            assert "org2/repo2/workflow2.ipynb" in lines[1] and "50%" in lines[1]

            print(f"✓ Multiple notebook test passed")
            print(f"✓ UI output:\n{ui_text}")

        except Exception as e:
            pytest.fail(f"Multiple notebook test failed: {e}")
        finally:
            # Restore mock
            tool.llm_provider.generate_structured = original_generate

            # Cleanup storage
            import shutil
            if storage_path.exists():
                shutil.rmtree(storage_path, ignore_errors=True)

    @pytest.mark.asyncio
    async def test_autonomous_mark_completion_ui_update(self, llm_interface):
        """Test AutonomousMarkCompletionTool sends UI update when all tasks are completed."""
        from kai.core.orchestration.base_tool import ToolOutputType

        tool = AutonomousMarkCompletionTool(llm_interface)

        # Test case 1: All tasks completed - should send UI update
        context_completed = self.create_basic_context(
            task_list={
                "tasks": [
                    {"id": 1, "task": "Load data", "status": "active"},
                    {"id": 2, "task": "Process data", "status": "pending"}
                ]
            },
            execution_result="All tasks have been completed successfully"
        )

        try:
            result = await tool.execute(context_completed)
            assert result is not None
            assert hasattr(result, 'output_ui')
            assert hasattr(result, 'output_type')

            # Should send UI update when all tasks are completed
            if all(task.get('status') == 'completed' for task in result.output_workflow.get('task_list', {}).get('tasks', [])):
                assert result.output_type == ToolOutputType.TASK_LIST_DISPLAY
                assert isinstance(result.output_ui, dict)
                assert 'text' in result.output_ui
                print(f"✓ All tasks completed - UI update sent: {result.output_type}")
            else:
                # Task might not be marked completed by LLM, that's ok for this test
                print(f"LLM didn't mark all tasks as completed, output_type: {result.output_type}")

        except Exception as e:
            pytest.fail(f"AutonomousMarkCompletionTool completion UI test failed: {e}")

        # Test case 2: Partial completion - should send UI update (behavior changed)
        context_partial = self.create_basic_context(
            task_list={
                "tasks": [
                    {"id": 1, "task": "Load data", "status": "active"},
                    {"id": 2, "task": "Process data", "status": "active"},
                    {"id": 3, "task": "Analyze data", "status": "pending"}
                ]
            },
            execution_result="First two tasks completed successfully"
        )

        try:
            result = await tool.execute(context_partial)
            assert result is not None

            # Should ALWAYS send UI update now (behavior changed)
            assert result.output_type == ToolOutputType.TASK_LIST_DISPLAY
            print(f"✓ Partial completion - UI update sent: {result.output_type}")

        except Exception as e:
            pytest.fail(f"AutonomousMarkCompletionTool partial completion test failed: {e}")

    @pytest.mark.asyncio
    async def test_reasoning_critique_tool_approved(self, llm_interface):
        """Test ReasoningCritiqueTool with APPROVED scenario."""
        tool = ReasoningCritiqueTool(llm_interface)
        context = self.create_basic_context(
            reasoning_response="Based on the analysis of the UMAP plot showing cells colored by donor_id, we observe clear clustering by donor identity, suggesting that batch effects from different donors are the primary source of variation in the data."
        )

        # Mock the tool's LLM provider to return APPROVED result
        original_generate_structured = tool.llm_provider.generate_structured

        async def mock_approved_response(*args, **kwargs):
            from kai.core.orchestration.schemas import ReasoningCritique
            return ReasoningCritique(
                approval="APPROVED",
                critique=""
            )

        tool.llm_provider.generate_structured = mock_approved_response

        try:
            result = await tool.execute(context)
            assert result is not None
            assert hasattr(result, 'output_workflow')

            workflow_output = result.output_workflow
            assert "reasoning_approval" in workflow_output
            assert "reasoning_critique" in workflow_output
            assert workflow_output["reasoning_approval"] == "APPROVED"
            assert workflow_output["reasoning_critique"] == ""

            # For approved reasoning with no critique, should have NO_OUTPUT
            assert result.output_type == ToolOutputType.NO_OUTPUT
            assert result.output_ui == {}

            print(f"ReasoningCritiqueTool APPROVED result: {workflow_output}")

        finally:
            tool.llm_provider.generate_structured = original_generate_structured

    @pytest.mark.asyncio
    async def test_reasoning_critique_tool_modify(self, llm_interface):
        """Test ReasoningCritiqueTool with MODIFY scenario."""
        tool = ReasoningCritiqueTool(llm_interface)
        context = self.create_basic_context(
            reasoning_response="The UMAP shows some clustering."
        )

        # Mock the tool's LLM provider to return MODIFY result
        original_generate_structured = tool.llm_provider.generate_structured

        async def mock_modify_response(*args, **kwargs):
            from kai.core.orchestration.schemas import ReasoningCritique
            return ReasoningCritique(
                approval="MODIFY",
                critique="The reasoning is too vague and lacks specific observations. Please include: (1) quantitative metrics if available, (2) specific visual observations from the UMAP, and (3) consideration of alternative explanations."
            )

        tool.llm_provider.generate_structured = mock_modify_response

        try:
            result = await tool.execute(context)
            assert result is not None

            workflow_output = result.output_workflow
            assert workflow_output["reasoning_approval"] == "MODIFY"
            assert len(workflow_output["reasoning_critique"]) > 0

            # For MODIFY, should send critique to UI
            assert result.output_type == ToolOutputType.TASK_LIST_DISPLAY
            assert "critique" in result.output_ui
            assert result.output_ui["critique"] == workflow_output["reasoning_critique"]

            print(f"ReasoningCritiqueTool MODIFY result: {workflow_output}")

        finally:
            tool.llm_provider.generate_structured = original_generate_structured

    @pytest.mark.asyncio
    async def test_reasoning_critique_tool_empty_critique(self, llm_interface):
        """Test ReasoningCritiqueTool validation: MODIFY requires critique."""
        tool = ReasoningCritiqueTool(llm_interface)
        context = self.create_basic_context(
            reasoning_response="Some reasoning text."
        )

        # Mock the tool's LLM provider to return invalid MODIFY with empty critique
        original_generate_structured = tool.llm_provider.generate_structured

        async def mock_invalid_response(*args, **kwargs):
            from kai.core.orchestration.schemas import ReasoningCritique
            return ReasoningCritique(
                approval="MODIFY",
                critique=""  # Invalid: empty critique with MODIFY
            )

        tool.llm_provider.generate_structured = mock_invalid_response

        try:
            with pytest.raises(ValueError, match="MODIFY approval requires a critique"):
                await tool.execute(context)
            print("✓ ReasoningCritiqueTool correctly raises ValueError for MODIFY without critique")

        finally:
            tool.llm_provider.generate_structured = original_generate_structured